# Generated by Django 4.2 on 2023-05-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
        ),
    ]
