version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "fun_and_curious"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwertz"
    volumes:
      - "/var/lib/postgresql/data"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py makemigrations
            python manage.py migrate
            python manage.py init_data
            python manage.py runserver 0.0.0.0:4000"
    volumes:
      - .:/fun_and_curious
    ports:
      - "4000:4000"
    depends_on:
      - db