# Generated by Django 4.2 on 2024-01-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
