# """
# Django settings for fun_and_curious project.
#
# Generated by 'django-admin startproject' using Django 4.2.1.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """
#

from fun_and_curious.settings import *
