# Generated by Django 4.2 on 2024-06-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_game_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")], null=True
            ),
        ),
    ]
