# Generated by Django 4.2.13 on 2024-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_game_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=255,
                null=True,
            ),
        ),
    ]
