# Generated by Django 4.2.13 on 2024-11-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_category_label_de_category_label_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="label_fr",
        ),
        migrations.RemoveField(
            model_name="question",
            name="label_fr",
        ),
    ]
