# Generated by Django 4.2.13 on 2024-11-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_remove_category_label_fr_remove_question_label_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="label_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label_fr",
            field=models.TextField(null=True),
        ),
    ]
